### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by itwars** [yesyayen/Website-Uptime-Monitor#2]
Hello,

config file is missing, could you please tell me what is the format with an example ?

Many thanks,
Vincnet

**Comment by yesyayen** [comment]
Oops. Thank you for pointing that out. Added the file.

Here it is https://github.com/yesyayen/Website-Uptime-Monitor/blob/master/config.js

To enable sending alerts, un-comment line 144 in https://github.com/yesyayen/Website-Uptime-Monitor/blob/aabfe365c6c3e386a357db14a0687e26cebe4188/server/controllers/websitelist-controller.js

**Comment by itwars** [comment]
Hello,

Thanks it works like a charm!
